apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
namePrefix: dev-
resources:
  - ../../base
  - 10_istio_route.yaml
  -
patchesStrategicMerge:
  - 11_patch_replicas.yaml

#configMapGenerator:
#- files:
#  - application-k8s.yml
#  name: single-config
images:
  - name: single
    newName: localhost:5000/elliot/single/k8s
    newTag: latest

generators:
  #  - merger.yaml
  - merger_remote.yaml