server:
  port: 8080
spring:
  application:
    name: trace-svc
#  r2dbc:
#    url: r2dbc:postgresql://127.0.0.1:5432/postgres
#    username: postgres
#    password: postgres
#  datasource:
#    username: postgres
#    password: postgres
#    url: jdbc:postgresql://127.0.0.1:5432/postgres
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

#logging.pattern.level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p
#otel:
#  exporter:
#    otlp:
#    endpoint: "http://localhost:4317"
#  traces:
#    sampler: 1.0
#  propagation: tracecontext
logging:
  pattern:
    #level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"
    level: "[${spring.application.name:},%X{trace_id:-},%X{span_id:-}] %5p"
