apiVersion: v1
kind: Pod
metadata:
  name: app-hostpath
spec:
  containers:
  - image: alpine
    name: app
    command: ["/bin/sh"]
    args: ["-c", "echo 'test pvc' >> /mnt/pod/data/test_pvc.txt;while true; do sleep 60; done;"]
    volumeMounts:
      - mountPath: "/mnt/pod/data"
        name: app-storage
  volumes:
    - name: app-storage
      hostPath:
        path: "/data/node"
        type: Directory