spring:
  datasource:
    username: postgres
    #password: postgres
    password: ${SECRETS_POSTGRES_PASSWORD}
    url: jdbc:postgresql://postgres-svc:5432/postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      repositories:
        enabled: true
      host: redis-svc
      port: 6379
apps:
  app01:
    url: https://app01-svc:8080/app01
  app02:
    url: https://app02-svc:8080/app01