apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/node
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: app-consuming-pvc
spec:
  containers:
  - image: alpine
    name: app01
    command: ["/bin/sh"]
    args: ["-c", "echo 'test pvc' >> /mnt/pod/data/test_pvc.txt;while true; do sleep 60; done;"]
    volumeMounts:
      - mountPath: "/mnt/pod/data"
        name: app-storage
  volumes:
    - name: app-storage
      persistentVolumeClaim:
        claimName: db-pvc