server:
  port: 8080
spring:
  application:
    name: department-svc
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: postgres
  kafka:
    bootstrapServers: localhost:9092
    producer:
      retries: 1
    consumer:
      groupId: spring
      enableAutoCommit: true
#logging.pattern.level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"

service:
  employee:
    url: "http://localhost:8081/employee"