spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/postgres
  jpa:
    hibernate:
#      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  datasource:
#    username: root
#    password: abcd1234
#    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  data:
#    redis:
#      repositories:
#        enabled: true
#      host: 127.0.0.1
#      port: 6379

#otel:
#  instrumentation:
#    spring-webmvc:
#      enabled: true
#  exporter:
#    logging:
#      enabled: true
#  springboot:
#    resource:
#      enabled: true
#  resource:
#    attributes:
#      environment: local