spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgresql:5432/postgres
  jpa:
#    hibernate:
#      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  datasource:
#    username: root
#    password: abcd1234
#    url: jdbc:mysql://mysql:3306/test?serverTimezone=UTC
#  jpa:
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#  data:
#    redis:
#      repositories:
#        enabled: true
#      host: redis
#      port: 6379